version: "3"
# docker-compose -f docker-compose.yml up --detach --build  ## for recreating the change
services:
  am-api:
    image: zelejs/allin-web:jdk11
    container_name: am-api
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps  
      - ./gateway/attachments:/attachments
    environment:
      DL_STANDALONE: "am-pack-1.0.0-standalone.jar"

  am-io:
    image: zelejs/allin-web:jdk11
    container_name: am-io
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./io:/webapps
    environment:
      DL_STANDALONE: "pdf-export-1.0.0-standalone.jar"

  am-web:
    image: daocloud.io/library/nginx:latest
    container_name: am-web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./web/dist:/usr/share/nginx/html
      - ./web/logs:/var/log/nginx
 
  am-gateway:
    image: daocloud.io/library/nginx:latest
    container_name: nginx-gateway
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/conf.d:/etc/nginx/conf.d
      - ./gateway/logs:/var/log/nginx
      - ./gateway/images:/usr/share/nginx/html/images
      - ./gateway/cert:/cert
      - ./gateway/html:/usr/share/nginx/html
      - ./gateway/attachments:/usr/share/nginx/html/attachments
    ports:
      - '8070:8070'

  am-redis:
    container_name: am-redis
    image: 'daocloud.io/library/redis:3.2.9'
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command:
      redis-server /usr/local/etc/redis/redis.conf
  
  swagger:
    image: zelejs/swagger
    container_name: swagger
    privileged: true
    volumes:
      - ./swagger/app:/swagger/app
