---
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://120.24.235.88:3306/am?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: zb
      password: zb2014
      filters: log4j,wall,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: false

logging:
  level: warn 
  config: config/logback-spring.xml
