version: "3"
services:
  api:
    image: zelejs/allin-web:jre11
    container_name: demo-api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./web/dist:/var/www/html  
      - ./api:/webapps  
      - ./swagger/app:/swagger/app
    ports:
      - 8080:8080  
      - 8000:80 
    depends_on:
      - mysql
    links:
      - mysql:mysqlserver
    environment:
      #GREENFIELD: run
      ENDPOINT: 192.168.3.10:8080
      URL_SHORT: mysqlserver:3306/test
      USERNAME: root
      PASSWORD: root

  mysql:
    image: zelejs/mysql:5.7
    container_name: mysql57
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
    volumes:
      - mydata:/var/lib/mysql
      #- /var/local/mysql/logs:/var/log/mysql
    ports:
      - '172.17.0.1:3306:3306'

volumes:
  mydata:
